module.exports = {
	PLUS: 'PLUS',
	MINUS: 'MINUS',
	EQUAL: 'EQUAL',
	TIMES: 'TIMES',
	DIVIDE: 'DIVIDE',
	REMAINDER: 'REMAINDER',
	NULL: 'NULL',
	LESS_THAN: 'LESS_THAN',
	GREATER_THAN: 'GREATER_THAN',
	MOVE: 'MOVE',
	DRAW: 'DRAW',
	TURN: 'TURN'
};
