module.exports = {
	PLUS: 'PLUS',
	MINUS: 'MINUS',
	TIMES: 'TIMES',
	DIVIDE: 'DIVIDE',
	REMAINDER: 'REMAINDER',

	EQUAL: 'EQUAL',
	NOT_EQUAL: 'NOT_EQUAL',
	LESS_EQUAL: 'LESS_EQUAL',
	LESS_THAN: 'LESS_THAN',
	GREATER_THAN: 'GREATER_THAN',
	GREATER_EQUAL: 'GREATER_EQUAL',

	RANDOM: 'RANDOM',

	NULL: 'NULL',

	MOVE: 'MOVE',
	DRAW: 'DRAW',
	TURN: 'TURN'
};
